// This file is auto-generated by @hey-api/openapi-ts

export const Body_login_api_v1_auth_login_postSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login_api_v1_auth_login_post'
} as const;

export const Body_upload_listing_image_api_v1_listings__listing_id__images_postSchema = {
    properties: {
        file: {
            type: 'string',
            contentMediaType: 'application/octet-stream',
            title: 'File'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_upload_listing_image_api_v1_listings__listing_id__images_post'
} as const;

export const CategoryCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        slug: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Slug'
        },
        parent_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parent Id'
        },
        icon_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Icon Url'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'CategoryCreate'
} as const;

export const CategoryReadSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        slug: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Slug'
        },
        parent_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parent Id'
        },
        icon_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Icon Url'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['name', 'id', 'created_at'],
    title: 'CategoryRead'
} as const;

export const CategoryTreeSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        slug: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Slug'
        },
        parent_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parent Id'
        },
        icon_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Icon Url'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        children: {
            items: {
                '$ref': '#/components/schemas/CategoryTree'
            },
            type: 'array',
            title: 'Children',
            default: []
        }
    },
    type: 'object',
    required: ['name', 'id', 'created_at'],
    title: 'CategoryTree'
} as const;

export const CategoryUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        slug: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Slug'
        },
        parent_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parent Id'
        },
        icon_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Icon Url'
        }
    },
    type: 'object',
    title: 'CategoryUpdate'
} as const;

export const ConditionGradeSchema = {
    type: 'string',
    enum: ['brand_new', 'like_new', 'good', 'fair', 'poor'],
    title: 'ConditionGrade'
} as const;

export const EscrowAdminResolveRequestSchema = {
    properties: {
        result: {
            type: 'string',
            pattern: '^(release|refund)$',
            title: 'Result'
        },
        note: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Note'
        }
    },
    type: 'object',
    required: ['result'],
    title: 'EscrowAdminResolveRequest'
} as const;

export const EscrowDisputeRequestSchema = {
    properties: {
        note: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Note'
        }
    },
    type: 'object',
    title: 'EscrowDisputeRequest'
} as const;

export const EscrowReadSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        order_id: {
            type: 'string',
            format: 'uuid',
            title: 'Order Id'
        },
        buyer_id: {
            type: 'string',
            format: 'uuid',
            title: 'Buyer Id'
        },
        seller_id: {
            type: 'string',
            format: 'uuid',
            title: 'Seller Id'
        },
        amount: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Amount'
        },
        status: {
            '$ref': '#/components/schemas/EscrowStatus'
        },
        funded_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Funded At'
        },
        released_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Released At'
        },
        refunded_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Refunded At'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['id', 'order_id', 'buyer_id', 'seller_id', 'amount', 'status', 'funded_at', 'released_at', 'refunded_at', 'created_at', 'updated_at'],
    title: 'EscrowRead'
} as const;

export const EscrowStatusSchema = {
    type: 'string',
    enum: ['awaiting_funding', 'held', 'release_pending', 'released', 'refunded', 'disputed'],
    title: 'EscrowStatus'
} as const;

export const ForgotPasswordRequestSchema = {
    properties: {
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        }
    },
    type: 'object',
    required: ['email'],
    title: 'ForgotPasswordRequest'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ListingCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 500,
            minLength: 5,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        price: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*(?:\\d{0,10}|(?=[\\d.]{1,13}0*$)\\d{0,10}\\.\\d{0,2}0*$)'
                }
            ],
            title: 'Price'
        },
        is_negotiable: {
            type: 'boolean',
            title: 'Is Negotiable',
            default: true
        },
        condition_grade: {
            '$ref': '#/components/schemas/ConditionGrade'
        },
        category_id: {
            type: 'string',
            format: 'uuid',
            title: 'Category Id'
        }
    },
    type: 'object',
    required: ['title', 'price', 'condition_grade', 'category_id'],
    title: 'ListingCreate'
} as const;

export const ListingImageReadSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        image_url: {
            type: 'string',
            title: 'Image Url'
        },
        is_primary: {
            type: 'boolean',
            title: 'Is Primary'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'image_url', 'is_primary', 'created_at'],
    title: 'ListingImageRead'
} as const;

export const ListingPaginatedSchema = {
    properties: {
        items: {
            items: {
                '$ref': '#/components/schemas/ListingWithImages'
            },
            type: 'array',
            title: 'Items'
        },
        total: {
            type: 'integer',
            title: 'Total'
        },
        page: {
            type: 'integer',
            title: 'Page'
        },
        size: {
            type: 'integer',
            title: 'Size'
        }
    },
    type: 'object',
    required: ['items', 'total', 'page', 'size'],
    title: 'ListingPaginated'
} as const;

export const ListingReadSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 500,
            minLength: 5,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        price: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*(?:\\d{0,10}|(?=[\\d.]{1,13}0*$)\\d{0,10}\\.\\d{0,2}0*$)',
            title: 'Price'
        },
        is_negotiable: {
            type: 'boolean',
            title: 'Is Negotiable',
            default: true
        },
        condition_grade: {
            '$ref': '#/components/schemas/ConditionGrade'
        },
        category_id: {
            type: 'string',
            format: 'uuid',
            title: 'Category Id'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        seller_id: {
            type: 'string',
            format: 'uuid',
            title: 'Seller Id'
        },
        status: {
            '$ref': '#/components/schemas/ListingStatus'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['title', 'price', 'condition_grade', 'category_id', 'id', 'seller_id', 'status', 'created_at', 'updated_at'],
    title: 'ListingRead'
} as const;

export const ListingStatusSchema = {
    type: 'string',
    enum: ['pending', 'active', 'sold', 'hidden', 'rejected'],
    title: 'ListingStatus'
} as const;

export const ListingUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500,
                    minLength: 5
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        price: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*(?:\\d{0,10}|(?=[\\d.]{1,13}0*$)\\d{0,10}\\.\\d{0,2}0*$)'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Price'
        },
        is_negotiable: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Negotiable'
        },
        condition_grade: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ConditionGrade'
                },
                {
                    type: 'null'
                }
            ]
        },
        category_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category Id'
        },
        status: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ListingStatus'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    title: 'ListingUpdate'
} as const;

export const ListingWithImagesSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 500,
            minLength: 5,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        price: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*(?:\\d{0,10}|(?=[\\d.]{1,13}0*$)\\d{0,10}\\.\\d{0,2}0*$)',
            title: 'Price'
        },
        is_negotiable: {
            type: 'boolean',
            title: 'Is Negotiable',
            default: true
        },
        condition_grade: {
            '$ref': '#/components/schemas/ConditionGrade'
        },
        category_id: {
            type: 'string',
            format: 'uuid',
            title: 'Category Id'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        seller_id: {
            type: 'string',
            format: 'uuid',
            title: 'Seller Id'
        },
        status: {
            '$ref': '#/components/schemas/ListingStatus'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        images: {
            items: {
                '$ref': '#/components/schemas/ListingImageRead'
            },
            type: 'array',
            title: 'Images',
            default: []
        }
    },
    type: 'object',
    required: ['title', 'price', 'condition_grade', 'category_id', 'id', 'seller_id', 'status', 'created_at', 'updated_at'],
    title: 'ListingWithImages'
} as const;

export const NotificationReadSchema = {
    properties: {
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        type: {
            '$ref': '#/components/schemas/NotificationType'
        },
        title: {
            type: 'string',
            maxLength: 255,
            title: 'Title'
        },
        message: {
            type: 'string',
            title: 'Message'
        },
        data: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Data'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        is_read: {
            type: 'boolean',
            title: 'Is Read'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['user_id', 'type', 'title', 'message', 'id', 'is_read', 'created_at'],
    title: 'NotificationRead'
} as const;

export const NotificationTypeSchema = {
    type: 'string',
    enum: ['offer_received', 'offer_accepted', 'offer_rejected', 'offer_countered', 'offer_expired', 'order_created', 'order_completed', 'order_cancelled', 'escrow_funded', 'escrow_release_requested', 'escrow_released', 'escrow_disputed', 'escrow_resolved', 'listing_approved', 'listing_rejected', 'review_received'],
    title: 'NotificationType'
} as const;

export const OfferCreateSchema = {
    properties: {
        offer_price: {
            anyOf: [
                {
                    type: 'number',
                    exclusiveMinimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d{0,2}0*$'
                }
            ],
            title: 'Offer Price',
            description: 'The price offered by the buyer'
        },
        listing_id: {
            type: 'string',
            format: 'uuid',
            title: 'Listing Id',
            description: 'The listing ID to make an offer on'
        }
    },
    type: 'object',
    required: ['offer_price', 'listing_id'],
    title: 'OfferCreate'
} as const;

export const OfferReadSchema = {
    properties: {
        offer_price: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d{0,2}0*$',
            title: 'Offer Price',
            description: 'The price offered by the buyer'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        listing_id: {
            type: 'string',
            format: 'uuid',
            title: 'Listing Id'
        },
        buyer_id: {
            type: 'string',
            format: 'uuid',
            title: 'Buyer Id'
        },
        status: {
            '$ref': '#/components/schemas/OfferStatus'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['offer_price', 'id', 'listing_id', 'buyer_id', 'status', 'created_at', 'updated_at'],
    title: 'OfferRead'
} as const;

export const OfferStatusSchema = {
    type: 'string',
    enum: ['pending', 'accepted', 'rejected', 'countered', 'expired'],
    title: 'OfferStatus'
} as const;

export const OfferStatusUpdateSchema = {
    properties: {
        status: {
            '$ref': '#/components/schemas/OfferStatus',
            description: 'New status for the offer (ACCEPTED, REJECTED, COUNTERED)'
        },
        offer_price: {
            anyOf: [
                {
                    type: 'number',
                    exclusiveMinimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d{0,2}0*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Offer Price'
        }
    },
    type: 'object',
    required: ['status'],
    title: 'OfferStatusUpdate'
} as const;

export const OrderDirectCreateSchema = {
    properties: {
        listing_id: {
            type: 'string',
            format: 'uuid',
            title: 'Listing Id'
        },
        use_escrow: {
            type: 'boolean',
            title: 'Use Escrow',
            default: false
        }
    },
    type: 'object',
    required: ['listing_id'],
    title: 'OrderDirectCreate'
} as const;

export const OrderReadSchema = {
    properties: {
        final_price: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d{0,2}0*$',
            title: 'Final Price'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        buyer_id: {
            type: 'string',
            format: 'uuid',
            title: 'Buyer Id'
        },
        seller_id: {
            type: 'string',
            format: 'uuid',
            title: 'Seller Id'
        },
        listing_id: {
            type: 'string',
            format: 'uuid',
            title: 'Listing Id'
        },
        status: {
            '$ref': '#/components/schemas/OrderStatus'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['final_price', 'id', 'buyer_id', 'seller_id', 'listing_id', 'status', 'created_at', 'updated_at'],
    title: 'OrderRead'
} as const;

export const OrderStatusSchema = {
    type: 'string',
    enum: ['pending', 'completed', 'cancelled', 'disputed'],
    title: 'OrderStatus'
} as const;

export const RefreshRequestSchema = {
    properties: {
        refresh_token: {
            type: 'string',
            title: 'Refresh Token'
        }
    },
    type: 'object',
    required: ['refresh_token'],
    title: 'RefreshRequest'
} as const;

export const RegisterRequestSchema = {
    properties: {
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            type: 'string',
            maxLength: 255,
            minLength: 2,
            title: 'Full Name'
        },
        phone: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone'
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'RegisterRequest'
} as const;

export const RegisterResponseSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'RegisterResponse'
} as const;

export const ResendVerificationRequestSchema = {
    properties: {
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        }
    },
    type: 'object',
    required: ['email'],
    title: 'ResendVerificationRequest'
} as const;

export const ResetPasswordRequestSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'ResetPasswordRequest'
} as const;

export const ReviewCreateSchema = {
    properties: {
        order_id: {
            type: 'string',
            format: 'uuid',
            title: 'Order Id'
        },
        rating: {
            type: 'integer',
            maximum: 5,
            minimum: 1,
            title: 'Rating'
        },
        comment: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Comment'
        }
    },
    type: 'object',
    required: ['order_id', 'rating'],
    title: 'ReviewCreate'
} as const;

export const ReviewReadSchema = {
    properties: {
        order_id: {
            type: 'string',
            format: 'uuid',
            title: 'Order Id'
        },
        rating: {
            type: 'integer',
            maximum: 5,
            minimum: 1,
            title: 'Rating'
        },
        comment: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Comment'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        reviewer_id: {
            type: 'string',
            format: 'uuid',
            title: 'Reviewer Id'
        },
        reviewee_id: {
            type: 'string',
            format: 'uuid',
            title: 'Reviewee Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['order_id', 'rating', 'id', 'reviewer_id', 'reviewee_id', 'created_at'],
    title: 'ReviewRead'
} as const;

export const TokenResponseSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        refresh_token: {
            type: 'string',
            title: 'Refresh Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        },
        user: {
            '$ref': '#/components/schemas/UserPublicResponse'
        }
    },
    type: 'object',
    required: ['access_token', 'refresh_token', 'user'],
    title: 'TokenResponse'
} as const;

export const UserMeSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        phone: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone'
        },
        avatar_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avatar Url'
        },
        bio: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bio'
        },
        province: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Province'
        },
        district: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'District'
        },
        ward: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ward'
        },
        address_detail: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Address Detail'
        },
        is_phone_verified: {
            type: 'boolean',
            title: 'Is Phone Verified'
        },
        is_email_verified: {
            type: 'boolean',
            title: 'Is Email Verified'
        },
        trust_score: {
            type: 'number',
            title: 'Trust Score'
        },
        rating_avg: {
            type: 'number',
            title: 'Rating Avg'
        },
        rating_count: {
            type: 'integer',
            title: 'Rating Count'
        },
        completed_orders: {
            type: 'integer',
            title: 'Completed Orders'
        },
        role: {
            type: 'string',
            title: 'Role'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['id', 'email', 'full_name', 'is_phone_verified', 'is_email_verified', 'trust_score', 'rating_avg', 'rating_count', 'completed_orders', 'role', 'is_active', 'created_at', 'updated_at'],
    title: 'UserMe',
    description: 'Full user info returned to the authenticated user (GET /users/me).'
} as const;

export const UserPublicProfileSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        avatar_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avatar Url'
        },
        bio: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bio'
        },
        province: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Province'
        },
        district: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'District'
        },
        trust_score: {
            type: 'number',
            title: 'Trust Score'
        },
        rating_avg: {
            type: 'number',
            title: 'Rating Avg'
        },
        rating_count: {
            type: 'integer',
            title: 'Rating Count'
        },
        completed_orders: {
            type: 'integer',
            title: 'Completed Orders'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'full_name', 'trust_score', 'rating_avg', 'rating_count', 'completed_orders', 'created_at'],
    title: 'UserPublicProfile'
} as const;

export const UserPublicResponseSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        avatar_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avatar Url'
        },
        role: {
            type: 'string',
            title: 'Role'
        },
        trust_score: {
            type: 'number',
            title: 'Trust Score'
        },
        rating_avg: {
            type: 'number',
            title: 'Rating Avg'
        },
        rating_count: {
            type: 'integer',
            title: 'Rating Count'
        },
        completed_orders: {
            type: 'integer',
            title: 'Completed Orders'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'email', 'full_name', 'role', 'trust_score', 'rating_avg', 'rating_count', 'completed_orders'],
    title: 'UserPublicResponse'
} as const;

export const UserStatusUpdateSchema = {
    properties: {
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        }
    },
    type: 'object',
    required: ['is_active'],
    title: 'UserStatusUpdate',
    description: 'Schema for updating user active status by Admin.'
} as const;

export const UserUpdateSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 2
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        phone: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone'
        },
        avatar_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avatar Url'
        },
        bio: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bio'
        },
        province: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Province'
        },
        district: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'District'
        },
        ward: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ward'
        },
        address_detail: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Address Detail'
        }
    },
    type: 'object',
    title: 'UserUpdate',
    description: 'Schema for updating user profile info (PUT /users/me).'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const VerifyEmailRequestSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        }
    },
    type: 'object',
    required: ['token'],
    title: 'VerifyEmailRequest'
} as const;

export const WalletAccountReadSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        available_balance: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Available Balance'
        },
        locked_balance: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Locked Balance'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['id', 'user_id', 'available_balance', 'locked_balance', 'created_at', 'updated_at'],
    title: 'WalletAccountRead'
} as const;

export const WalletDemoTopupRequestSchema = {
    properties: {
        amount: {
            anyOf: [
                {
                    type: 'number',
                    exclusiveMinimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d{0,2}0*$'
                }
            ],
            title: 'Amount'
        }
    },
    type: 'object',
    required: ['amount'],
    title: 'WalletDemoTopupRequest'
} as const;

export const WalletTransactionDirectionSchema = {
    type: 'string',
    enum: ['credit', 'debit'],
    title: 'WalletTransactionDirection'
} as const;

export const WalletTransactionReadSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        order_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Order Id'
        },
        type: {
            '$ref': '#/components/schemas/WalletTransactionType'
        },
        direction: {
            '$ref': '#/components/schemas/WalletTransactionDirection'
        },
        amount: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Amount'
        },
        balance_after: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Balance After'
        },
        metadata: {
            additionalProperties: true,
            type: 'object',
            title: 'Metadata'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'user_id', 'order_id', 'type', 'direction', 'amount', 'balance_after', 'metadata', 'created_at'],
    title: 'WalletTransactionRead'
} as const;

export const WalletTransactionTypeSchema = {
    type: 'string',
    enum: ['topup_demo', 'hold', 'release', 'refund', 'adjustment'],
    title: 'WalletTransactionType'
} as const;