// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_api_v1_auth_login_post = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_upload_listing_image_api_v1_listings__listing_id__images_post = {
    file: string;
};

export type CategoryCreate = {
    name: string;
    slug?: (string | null);
    parent_id?: (string | null);
    icon_url?: (string | null);
};

export type CategoryRead = {
    name: string;
    slug?: (string | null);
    parent_id?: (string | null);
    icon_url?: (string | null);
    id: string;
    created_at: string;
};

export type CategoryTree = {
    name: string;
    slug?: (string | null);
    parent_id?: (string | null);
    icon_url?: (string | null);
    id: string;
    created_at: string;
    children?: Array<CategoryTree>;
};

export type CategoryUpdate = {
    name?: (string | null);
    slug?: (string | null);
    parent_id?: (string | null);
    icon_url?: (string | null);
};

export type ConditionGrade = 'brand_new' | 'like_new' | 'good' | 'fair' | 'poor';

export const ConditionGrade = {
    BRAND_NEW: 'brand_new',
    LIKE_NEW: 'like_new',
    GOOD: 'good',
    FAIR: 'fair',
    POOR: 'poor'
} as const;

export type EscrowAdminResolveRequest = {
    result: string;
    note?: (string | null);
};

export type EscrowDisputeRequest = {
    note?: (string | null);
};

export type EscrowRead = {
    id: string;
    order_id: string;
    buyer_id: string;
    seller_id: string;
    amount: string;
    status: EscrowStatus;
    funded_at: (string | null);
    released_at: (string | null);
    refunded_at: (string | null);
    created_at: string;
    updated_at: string;
};

export type EscrowStatus = 'awaiting_funding' | 'held' | 'release_pending' | 'released' | 'refunded' | 'disputed';

export const EscrowStatus = {
    AWAITING_FUNDING: 'awaiting_funding',
    HELD: 'held',
    RELEASE_PENDING: 'release_pending',
    RELEASED: 'released',
    REFUNDED: 'refunded',
    DISPUTED: 'disputed'
} as const;

export type ForgotPasswordRequest = {
    email: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ListingCreate = {
    title: string;
    description?: (string | null);
    price: (number | string);
    is_negotiable?: boolean;
    condition_grade: ConditionGrade;
    category_id: string;
};

export type ListingImageRead = {
    id: string;
    image_url: string;
    is_primary: boolean;
    created_at: string;
};

export type ListingPaginated = {
    items: Array<ListingWithImages>;
    total: number;
    page: number;
    size: number;
};

export type ListingRead = {
    title: string;
    description?: (string | null);
    price: string;
    is_negotiable?: boolean;
    condition_grade: ConditionGrade;
    category_id: string;
    id: string;
    seller_id: string;
    status: ListingStatus;
    created_at: string;
    updated_at: string;
};

export type ListingStatus = 'pending' | 'active' | 'sold' | 'hidden' | 'rejected';

export const ListingStatus = {
    PENDING: 'pending',
    ACTIVE: 'active',
    SOLD: 'sold',
    HIDDEN: 'hidden',
    REJECTED: 'rejected'
} as const;

export type ListingUpdate = {
    title?: (string | null);
    description?: (string | null);
    price?: (number | string | null);
    is_negotiable?: (boolean | null);
    condition_grade?: (ConditionGrade | null);
    category_id?: (string | null);
    status?: (ListingStatus | null);
};

export type ListingWithImages = {
    title: string;
    description?: (string | null);
    price: string;
    is_negotiable?: boolean;
    condition_grade: ConditionGrade;
    category_id: string;
    id: string;
    seller_id: string;
    status: ListingStatus;
    created_at: string;
    updated_at: string;
    images?: Array<ListingImageRead>;
};

export type NotificationRead = {
    user_id: string;
    type: NotificationType;
    title: string;
    message: string;
    data?: ({
    [key: string]: unknown;
} | null);
    id: string;
    is_read: boolean;
    created_at: string;
};

export type NotificationType = 'offer_received' | 'offer_accepted' | 'offer_rejected' | 'offer_countered' | 'offer_expired' | 'order_created' | 'order_completed' | 'order_cancelled' | 'escrow_funded' | 'escrow_release_requested' | 'escrow_released' | 'escrow_disputed' | 'escrow_resolved' | 'listing_approved' | 'listing_rejected' | 'review_received';

export const NotificationType = {
    OFFER_RECEIVED: 'offer_received',
    OFFER_ACCEPTED: 'offer_accepted',
    OFFER_REJECTED: 'offer_rejected',
    OFFER_COUNTERED: 'offer_countered',
    OFFER_EXPIRED: 'offer_expired',
    ORDER_CREATED: 'order_created',
    ORDER_COMPLETED: 'order_completed',
    ORDER_CANCELLED: 'order_cancelled',
    ESCROW_FUNDED: 'escrow_funded',
    ESCROW_RELEASE_REQUESTED: 'escrow_release_requested',
    ESCROW_RELEASED: 'escrow_released',
    ESCROW_DISPUTED: 'escrow_disputed',
    ESCROW_RESOLVED: 'escrow_resolved',
    LISTING_APPROVED: 'listing_approved',
    LISTING_REJECTED: 'listing_rejected',
    REVIEW_RECEIVED: 'review_received'
} as const;

export type OfferCreate = {
    /**
     * The price offered by the buyer
     */
    offer_price: (number | string);
    /**
     * The listing ID to make an offer on
     */
    listing_id: string;
};

export type OfferRead = {
    /**
     * The price offered by the buyer
     */
    offer_price: string;
    id: string;
    listing_id: string;
    buyer_id: string;
    status: OfferStatus;
    created_at: string;
    updated_at: string;
};

export type OfferStatus = 'pending' | 'accepted' | 'rejected' | 'countered' | 'expired';

export const OfferStatus = {
    PENDING: 'pending',
    ACCEPTED: 'accepted',
    REJECTED: 'rejected',
    COUNTERED: 'countered',
    EXPIRED: 'expired'
} as const;

export type OfferStatusUpdate = {
    /**
     * New status for the offer (ACCEPTED, REJECTED, COUNTERED)
     */
    status: OfferStatus;
    offer_price?: (number | string | null);
};

export type OrderDirectCreate = {
    listing_id: string;
    use_escrow?: boolean;
};

export type OrderRead = {
    final_price: string;
    id: string;
    buyer_id: string;
    seller_id: string;
    listing_id: string;
    status: OrderStatus;
    created_at: string;
    updated_at: string;
};

export type OrderStatus = 'pending' | 'completed' | 'cancelled' | 'disputed';

export const OrderStatus = {
    PENDING: 'pending',
    COMPLETED: 'completed',
    CANCELLED: 'cancelled',
    DISPUTED: 'disputed'
} as const;

export type RefreshRequest = {
    refresh_token: string;
};

export type RegisterRequest = {
    email: string;
    password: string;
    full_name: string;
    phone?: (string | null);
};

export type RegisterResponse = {
    message: string;
};

export type ResendVerificationRequest = {
    email: string;
};

export type ResetPasswordRequest = {
    token: string;
    new_password: string;
};

export type ReviewCreate = {
    order_id: string;
    rating: number;
    comment?: (string | null);
};

export type ReviewRead = {
    order_id: string;
    rating: number;
    comment?: (string | null);
    id: string;
    reviewer_id: string;
    reviewee_id: string;
    created_at: string;
};

export type TokenResponse = {
    access_token: string;
    refresh_token: string;
    token_type?: string;
    user: UserPublicResponse;
};

/**
 * Full user info returned to the authenticated user (GET /users/me).
 */
export type UserMe = {
    id: string;
    email: string;
    full_name: string;
    phone?: (string | null);
    avatar_url?: (string | null);
    bio?: (string | null);
    province?: (string | null);
    district?: (string | null);
    ward?: (string | null);
    address_detail?: (string | null);
    is_phone_verified: boolean;
    is_email_verified: boolean;
    trust_score: number;
    rating_avg: number;
    rating_count: number;
    completed_orders: number;
    role: string;
    is_active: boolean;
    created_at: string;
    updated_at: string;
};

export type UserPublicProfile = {
    id: string;
    full_name: string;
    avatar_url?: (string | null);
    bio?: (string | null);
    province?: (string | null);
    district?: (string | null);
    trust_score: number;
    rating_avg: number;
    rating_count: number;
    completed_orders: number;
    created_at: string;
};

export type UserPublicResponse = {
    id: string;
    email: string;
    full_name: string;
    avatar_url?: (string | null);
    role: string;
    trust_score: number;
    rating_avg: number;
    rating_count: number;
    completed_orders: number;
    created_at?: (string | null);
};

/**
 * Schema for updating user active status by Admin.
 */
export type UserStatusUpdate = {
    is_active: boolean;
};

/**
 * Schema for updating user profile info (PUT /users/me).
 */
export type UserUpdate = {
    full_name?: (string | null);
    phone?: (string | null);
    avatar_url?: (string | null);
    bio?: (string | null);
    province?: (string | null);
    district?: (string | null);
    ward?: (string | null);
    address_detail?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type VerifyEmailRequest = {
    token: string;
};

export type WalletAccountRead = {
    id: string;
    user_id: string;
    available_balance: string;
    locked_balance: string;
    created_at: string;
    updated_at: string;
};

export type WalletDemoTopupRequest = {
    amount: (number | string);
};

export type WalletTransactionDirection = 'credit' | 'debit';

export const WalletTransactionDirection = {
    CREDIT: 'credit',
    DEBIT: 'debit'
} as const;

export type WalletTransactionRead = {
    id: string;
    user_id: string;
    order_id: (string | null);
    type: WalletTransactionType;
    direction: WalletTransactionDirection;
    amount: string;
    balance_after: string;
    metadata: {
        [key: string]: unknown;
    };
    created_at: string;
};

export type WalletTransactionType = 'topup_demo' | 'hold' | 'release' | 'refund' | 'adjustment';

export const WalletTransactionType = {
    TOPUP_DEMO: 'topup_demo',
    HOLD: 'hold',
    RELEASE: 'release',
    REFUND: 'refund',
    ADJUSTMENT: 'adjustment'
} as const;

export type ListUsersApiV1AdminUsersGetData = {
    limit?: number;
    skip?: number;
};

export type ListUsersApiV1AdminUsersGetResponse = (Array<UserMe>);

export type UpdateUserAccountStatusApiV1AdminUsersUserIdStatusPatchData = {
    requestBody: UserStatusUpdate;
    userId: string;
};

export type UpdateUserAccountStatusApiV1AdminUsersUserIdStatusPatchResponse = (UserMe);

export type GetPendingListingsRouteApiV1AdminListingsPendingGetData = {
    limit?: number;
    skip?: number;
};

export type GetPendingListingsRouteApiV1AdminListingsPendingGetResponse = (Array<ListingRead>);

export type ListOrdersForAdminApiV1AdminOrdersGetData = {
    limit?: number;
    skip?: number;
};

export type ListOrdersForAdminApiV1AdminOrdersGetResponse = (Array<OrderRead>);

export type ApproveListingApiV1AdminListingsListingIdApprovePostData = {
    listingId: string;
};

export type ApproveListingApiV1AdminListingsListingIdApprovePostResponse = (ListingRead);

export type RejectListingRouteApiV1AdminListingsListingIdRejectPostData = {
    listingId: string;
};

export type RejectListingRouteApiV1AdminListingsListingIdRejectPostResponse = (ListingRead);

export type AdminCreateCategoryApiV1AdminCategoriesPostData = {
    requestBody: CategoryCreate;
};

export type AdminCreateCategoryApiV1AdminCategoriesPostResponse = (CategoryRead);

export type AdminUpdateCategoryApiV1AdminCategoriesCategoryIdPutData = {
    categoryId: string;
    requestBody: CategoryUpdate;
};

export type AdminUpdateCategoryApiV1AdminCategoriesCategoryIdPutResponse = (CategoryRead);

export type AdminDeleteCategoryApiV1AdminCategoriesCategoryIdDeleteData = {
    categoryId: string;
};

export type AdminDeleteCategoryApiV1AdminCategoriesCategoryIdDeleteResponse = (void);

export type RegisterApiV1AuthRegisterPostData = {
    requestBody: RegisterRequest;
};

export type RegisterApiV1AuthRegisterPostResponse = (RegisterResponse);

export type LoginApiV1AuthLoginPostData = {
    formData: Body_login_api_v1_auth_login_post;
};

export type LoginApiV1AuthLoginPostResponse = (TokenResponse);

export type RefreshAccessTokenApiV1AuthRefreshPostData = {
    requestBody: RefreshRequest;
};

export type RefreshAccessTokenApiV1AuthRefreshPostResponse = (TokenResponse);

export type VerifyEmailApiV1AuthVerifyEmailPostData = {
    requestBody: VerifyEmailRequest;
};

export type VerifyEmailApiV1AuthVerifyEmailPostResponse = (unknown);

export type ResendVerificationEmailApiV1AuthResendVerificationPostData = {
    requestBody: ResendVerificationRequest;
};

export type ResendVerificationEmailApiV1AuthResendVerificationPostResponse = (unknown);

export type ForgotPasswordApiV1AuthForgotPasswordPostData = {
    requestBody: ForgotPasswordRequest;
};

export type ForgotPasswordApiV1AuthForgotPasswordPostResponse = (unknown);

export type ResetPasswordApiV1AuthResetPasswordPostData = {
    requestBody: ResetPasswordRequest;
};

export type ResetPasswordApiV1AuthResetPasswordPostResponse = (unknown);

export type LogoutApiV1AuthLogoutPostResponse = (void);

export type GetCategoriesApiV1CategoriesGetData = {
    /**
     * Format the response as a tree
     */
    asTree?: boolean;
};

export type GetCategoriesApiV1CategoriesGetResponse = ((Array<CategoryTree> | Array<CategoryRead>));

export type CreateCategoryApiV1CategoriesPostData = {
    requestBody: CategoryCreate;
};

export type CreateCategoryApiV1CategoriesPostResponse = (CategoryRead);

export type GetCategoryApiV1CategoriesCategoryIdGetData = {
    categoryId: string;
};

export type GetCategoryApiV1CategoriesCategoryIdGetResponse = (CategoryRead);

export type UpdateCategoryApiV1CategoriesCategoryIdPutData = {
    categoryId: string;
    requestBody: CategoryUpdate;
};

export type UpdateCategoryApiV1CategoriesCategoryIdPutResponse = (CategoryRead);

export type DeleteCategoryApiV1CategoriesCategoryIdDeleteData = {
    categoryId: string;
};

export type DeleteCategoryApiV1CategoriesCategoryIdDeleteResponse = (void);

export type RootGetResponse = (unknown);

export type ListDisputedEscrowsApiV1EscrowsDisputedGetData = {
    limit?: number;
    skip?: number;
};

export type ListDisputedEscrowsApiV1EscrowsDisputedGetResponse = (Array<EscrowRead>);

export type GetEscrowByOrderApiV1EscrowsOrderIdGetData = {
    orderId: string;
};

export type GetEscrowByOrderApiV1EscrowsOrderIdGetResponse = (EscrowRead);

export type FundEscrowApiV1EscrowsOrderIdFundPostData = {
    orderId: string;
};

export type FundEscrowApiV1EscrowsOrderIdFundPostResponse = (EscrowRead);

export type RequestReleaseApiV1EscrowsOrderIdReleaseRequestPostData = {
    orderId: string;
};

export type RequestReleaseApiV1EscrowsOrderIdReleaseRequestPostResponse = (EscrowRead);

export type ConfirmReleaseApiV1EscrowsOrderIdConfirmReleasePostData = {
    orderId: string;
};

export type ConfirmReleaseApiV1EscrowsOrderIdConfirmReleasePostResponse = (EscrowRead);

export type OpenDisputeApiV1EscrowsOrderIdOpenDisputePostData = {
    orderId: string;
    requestBody: EscrowDisputeRequest;
};

export type OpenDisputeApiV1EscrowsOrderIdOpenDisputePostResponse = (EscrowRead);

export type AdminResolveEscrowApiV1EscrowsOrderIdAdminResolvePostData = {
    orderId: string;
    requestBody: EscrowAdminResolveRequest;
};

export type AdminResolveEscrowApiV1EscrowsOrderIdAdminResolvePostResponse = (EscrowRead);

export type ListListingsApiV1ListingsGetData = {
    categoryId?: (string | null);
    conditionGrade?: (ConditionGrade | null);
    district?: (string | null);
    keyword?: (string | null);
    limit?: number;
    maxPrice?: (number | null);
    minPrice?: (number | null);
    province?: (string | null);
    sellerId?: (string | null);
    sortBy?: ('newest' | 'price_asc' | 'price_desc');
    skip?: number;
};

export type ListListingsApiV1ListingsGetResponse = (ListingPaginated);

export type CreateListingApiV1ListingsPostData = {
    requestBody: ListingCreate;
};

export type CreateListingApiV1ListingsPostResponse = (ListingRead);

export type GetMyListingsApiV1ListingsMeGetData = {
    keyword?: (string | null);
    limit?: number;
    skip?: number;
    status?: (ListingStatus | null);
};

export type GetMyListingsApiV1ListingsMeGetResponse = (ListingPaginated);

export type DeleteListingImageRouteApiV1ListingsImagesImageIdDeleteData = {
    imageId: string;
};

export type DeleteListingImageRouteApiV1ListingsImagesImageIdDeleteResponse = (void);

export type GetListingApiV1ListingsListingIdGetData = {
    listingId: string;
};

export type GetListingApiV1ListingsListingIdGetResponse = (ListingWithImages);

export type UpdateListingApiV1ListingsListingIdPatchData = {
    listingId: string;
    requestBody: ListingUpdate;
};

export type UpdateListingApiV1ListingsListingIdPatchResponse = (ListingRead);

export type DeleteListingApiV1ListingsListingIdDeleteData = {
    listingId: string;
};

export type DeleteListingApiV1ListingsListingIdDeleteResponse = (void);

export type UploadListingImageApiV1ListingsListingIdImagesPostData = {
    formData: Body_upload_listing_image_api_v1_listings__listing_id__images_post;
    isPrimary?: boolean;
    listingId: string;
};

export type UploadListingImageApiV1ListingsListingIdImagesPostResponse = (ListingImageRead);

export type GetMyNotificationsApiV1NotificationsGetResponse = (Array<NotificationRead>);

export type GetUnreadNotificationsCountApiV1NotificationsUnreadCountGetResponse = (unknown);

export type MarkNotificationAsReadApiV1NotificationsNotificationIdReadPutData = {
    notificationId: string;
};

export type MarkNotificationAsReadApiV1NotificationsNotificationIdReadPutResponse = (NotificationRead);

export type MarkAllNotificationsAsReadApiV1NotificationsReadAllPutResponse = (unknown);

export type CreateOfferApiV1OffersPostData = {
    requestBody: OfferCreate;
};

export type CreateOfferApiV1OffersPostResponse = (OfferRead);

export type GetMySentOffersApiV1OffersMeSentGetData = {
    limit?: number;
    skip?: number;
};

export type GetMySentOffersApiV1OffersMeSentGetResponse = (Array<OfferRead>);

export type GetMyReceivedOffersApiV1OffersMeReceivedGetData = {
    limit?: number;
    skip?: number;
};

export type GetMyReceivedOffersApiV1OffersMeReceivedGetResponse = (Array<OfferRead>);

export type GetOffersForListingApiV1OffersListingListingIdGetData = {
    limit?: number;
    listingId: string;
    skip?: number;
};

export type GetOffersForListingApiV1OffersListingListingIdGetResponse = (Array<OfferRead>);

export type UpdateOfferStatusApiV1OffersOfferIdStatusPatchData = {
    offerId: string;
    requestBody: OfferStatusUpdate;
};

export type UpdateOfferStatusApiV1OffersOfferIdStatusPatchResponse = (OfferRead);

export type GetOfferApiV1OffersOfferIdGetData = {
    offerId: string;
};

export type GetOfferApiV1OffersOfferIdGetResponse = (OfferRead);

export type GetMyOrdersApiV1OrdersGetResponse = (Array<OrderRead>);

export type CreateDirectOrderApiV1OrdersPostData = {
    requestBody: OrderDirectCreate;
};

export type CreateDirectOrderApiV1OrdersPostResponse = (OrderRead);

export type GetMyOrdersApiV1OrdersMeGetResponse = (Array<OrderRead>);

export type GetOrderApiV1OrdersOrderIdGetData = {
    orderId: string;
};

export type GetOrderApiV1OrdersOrderIdGetResponse = (OrderRead);

export type CompleteOrderApiV1OrdersOrderIdCompletePostData = {
    orderId: string;
};

export type CompleteOrderApiV1OrdersOrderIdCompletePostResponse = (OrderRead);

export type CancelOrderApiV1OrdersOrderIdCancelPostData = {
    orderId: string;
};

export type CancelOrderApiV1OrdersOrderIdCancelPostResponse = (OrderRead);

export type CreateReviewApiV1ReviewsPostData = {
    requestBody: ReviewCreate;
};

export type CreateReviewApiV1ReviewsPostResponse = (ReviewRead);

export type GetUserReviewsApiV1ReviewsUserUserIdGetData = {
    userId: string;
};

export type GetUserReviewsApiV1ReviewsUserUserIdGetResponse = (Array<ReviewRead>);

export type GetReviewsForOrderApiV1ReviewsOrderIdGetData = {
    orderId: string;
};

export type GetReviewsForOrderApiV1ReviewsOrderIdGetResponse = (Array<ReviewRead>);

export type GetMyProfileApiV1UsersMeGetResponse = (UserMe);

export type UpdateMyProfileApiV1UsersMePutData = {
    requestBody: UserUpdate;
};

export type UpdateMyProfileApiV1UsersMePutResponse = (UserMe);

export type GetUserPublicProfileApiV1UsersUserIdProfileGetData = {
    userId: string;
};

export type GetUserPublicProfileApiV1UsersUserIdProfileGetResponse = (UserPublicProfile);

export type HealthCheckApiV1UtilsHealthCheckGetResponse = (unknown);

export type GetMyWalletApiV1WalletMeGetResponse = (WalletAccountRead);

export type TopupDemoWalletApiV1WalletDemoTopupPostData = {
    requestBody: WalletDemoTopupRequest;
};

export type TopupDemoWalletApiV1WalletDemoTopupPostResponse = (WalletAccountRead);

export type GetMyWalletTransactionsApiV1WalletTransactionsGetResponse = (Array<WalletTransactionRead>);