"""Init Base Models

Revision ID: 1af3dfac5e8b
Revises: 
Create Date: 2026-03-13 01:41:44.307743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1af3dfac5e8b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'icon_url',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('categories_parent_id_fkey'), 'categories', type_='foreignkey')
    op.create_foreign_key(None, 'categories', 'categories', ['parent_id'], ['id'])
    op.alter_column('listing_images', 'image_url',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('listing_images', 'is_primary',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('listing_images', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_listing_images_listing'), table_name='listing_images')
    op.alter_column('listings', 'description',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('listings', 'price',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('listings', 'is_negotiable',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('listings', 'condition_grade',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=True)
    op.alter_column('listings', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('listings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('listings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_listings_category'), table_name='listings')
    op.drop_index(op.f('idx_listings_seller'), table_name='listings')
    op.drop_index(op.f('idx_listings_status'), table_name='listings')
    op.drop_constraint(op.f('listings_seller_id_fkey'), 'listings', type_='foreignkey')
    op.create_foreign_key(None, 'listings', 'users', ['seller_id'], ['id'])
    op.alter_column('notifications', 'message',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_notifications_unread'), table_name='notifications', postgresql_where='(is_read = false)')
    op.drop_index(op.f('idx_notifications_user'), table_name='notifications')
    op.alter_column('offers', 'offer_price',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('offers', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('offers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('offers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_offers_buyer'), table_name='offers')
    op.drop_index(op.f('idx_offers_listing'), table_name='offers')
    op.drop_constraint(op.f('offers_buyer_id_fkey'), 'offers', type_='foreignkey')
    op.create_foreign_key(None, 'offers', 'users', ['buyer_id'], ['id'])
    op.alter_column('orders', 'final_price',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('orders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_orders_buyer'), table_name='orders')
    op.drop_index(op.f('idx_orders_listing'), table_name='orders')
    op.drop_index(op.f('idx_orders_seller'), table_name='orders')
    op.alter_column('reviews', 'comment',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('reviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_reviews_reviewee'), table_name='reviews')
    op.drop_index(op.f('idx_reviews_reviewer'), table_name='reviews')
    op.drop_constraint(op.f('reviews_order_id_fkey'), 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'orders', ['order_id'], ['id'])
    op.alter_column('users', 'avatar_url',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('users', 'bio',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('users', 'is_phone_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'is_email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'trust_score',
               existing_type=sa.NUMERIC(precision=5, scale=1),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('users', 'rating_avg',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('users', 'rating_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'completed_orders',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'user'::character varying"))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_index(op.f('idx_users_role'), table_name='users')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'role',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'user'::character varying"))
    op.alter_column('users', 'completed_orders',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'rating_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'rating_avg',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('users', 'trust_score',
               existing_type=sa.NUMERIC(precision=5, scale=1),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('users', 'is_email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'is_phone_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'bio',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'avatar_url',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key(op.f('reviews_order_id_fkey'), 'reviews', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_reviews_reviewer'), 'reviews', ['reviewer_id'], unique=False)
    op.create_index(op.f('idx_reviews_reviewee'), 'reviews', ['reviewee_id'], unique=False)
    op.alter_column('reviews', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('reviews', 'comment',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_index(op.f('idx_orders_seller'), 'orders', ['seller_id'], unique=False)
    op.create_index(op.f('idx_orders_listing'), 'orders', ['listing_id'], unique=False)
    op.create_index(op.f('idx_orders_buyer'), 'orders', ['buyer_id'], unique=False)
    op.alter_column('orders', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('orders', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('orders', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('orders', 'final_price',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=False)
    op.drop_constraint(None, 'offers', type_='foreignkey')
    op.create_foreign_key(op.f('offers_buyer_id_fkey'), 'offers', 'users', ['buyer_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_offers_listing'), 'offers', ['listing_id'], unique=False)
    op.create_index(op.f('idx_offers_buyer'), 'offers', ['buyer_id'], unique=False)
    op.alter_column('offers', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('offers', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('offers', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('offers', 'offer_price',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=False)
    op.create_index(op.f('idx_notifications_user'), 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('idx_notifications_unread'), 'notifications', ['user_id', 'is_read'], unique=False, postgresql_where='(is_read = false)')
    op.alter_column('notifications', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('notifications', 'message',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'listings', type_='foreignkey')
    op.create_foreign_key(op.f('listings_seller_id_fkey'), 'listings', 'users', ['seller_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_listings_status'), 'listings', ['status'], unique=False)
    op.create_index(op.f('idx_listings_seller'), 'listings', ['seller_id'], unique=False)
    op.create_index(op.f('idx_listings_category'), 'listings', ['category_id'], unique=False)
    op.alter_column('listings', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('listings', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('listings', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('listings', 'condition_grade',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('listings', 'is_negotiable',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('listings', 'price',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=False)
    op.alter_column('listings', 'description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_index(op.f('idx_listing_images_listing'), 'listing_images', ['listing_id'], unique=False)
    op.alter_column('listing_images', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('listing_images', 'is_primary',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('listing_images', 'image_url',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.create_foreign_key(op.f('categories_parent_id_fkey'), 'categories', 'categories', ['parent_id'], ['id'], ondelete='SET NULL')
    op.alter_column('categories', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('categories', 'icon_url',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
