"""Add proof image urls to fulfillment

Revision ID: d6cab8724a9f
Revises: 93a76695ae00
Create Date: 2026-05-15 10:04:28.004370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd6cab8724a9f'
down_revision: Union[str, Sequence[str], None] = '93a76695ae00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fulfillments', sa.Column('seller_proof_image_urls', sa.JSON(), nullable=True))
    op.add_column('fulfillments', sa.Column('buyer_proof_image_urls', sa.JSON(), nullable=True))
    op.drop_index(op.f('ix_listing_images_image_md5'), table_name='listing_images')
    op.drop_index(op.f('ix_listing_images_perceptual_hash'), table_name='listing_images')
    op.drop_column('orders', 'buyer_confirmed_received_at')
    op.drop_column('orders', 'fulfillment_status')
    op.drop_column('orders', 'seller_marked_delivered_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('seller_marked_delivered_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('fulfillment_status', postgresql.ENUM('created', 'awaiting_funding', 'funded', 'seller_marked_delivered', 'buyer_confirmed_received', 'disputed', 'resolved_refund', 'cancelled', name='fulfillment_status_enum'), server_default=sa.text("'created'::fulfillment_status_enum"), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('buyer_confirmed_received_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_listing_images_perceptual_hash'), 'listing_images', ['perceptual_hash'], unique=False)
    op.create_index(op.f('ix_listing_images_image_md5'), 'listing_images', ['image_md5'], unique=False)
    op.drop_column('fulfillments', 'buyer_proof_image_urls')
    op.drop_column('fulfillments', 'seller_proof_image_urls')
    # ### end Alembic commands ###
